namespace LascodiaTradingEngine.Domain.Enums;

/// <summary>
/// Categorises the condition that triggered an alert notification.
/// </summary>
public enum AlertType
{
    /// <summary>Price reached a user-defined level.</summary>
    PriceLevel = 0,

    /// <summary>Account drawdown exceeded the configured threshold.</summary>
    DrawdownBreached = 1,

    /// <summary>A new trade signal was generated by a strategy.</summary>
    SignalGenerated = 2,

    /// <summary>An order was filled at the broker.</summary>
    OrderFilled = 3,

    /// <summary>A position was closed (by SL, TP, or manual action).</summary>
    PositionClosed = 4,

    /// <summary>An ML model's prediction accuracy has degraded below threshold.</summary>
    MLModelDegraded = 5,

    /// <summary>Market data quality issue detected (gaps, stale ticks, etc.).</summary>
    DataQualityIssue = 6,

    /// <summary>Multiple ML models are degrading simultaneously, indicating systemic issues.</summary>
    SystemicMLDegradation = 7,

    /// <summary>Execution or data pipeline latency exceeded the SLA threshold.</summary>
    LatencySla = 8,

    /// <summary>An optimization lifecycle or recovery issue requires operator visibility.</summary>
    OptimizationLifecycleIssue = 9,

    /// <summary>A background worker has crashed (no heartbeat beyond its configured threshold).</summary>
    WorkerCrash = 10,

    /// <summary>All EA instances disconnected — market data unavailable.</summary>
    EADisconnected = 11,

    /// <summary>Worker configuration has drifted from what code requires (e.g. mismatched
    /// embedding dimension, missing implementation for a configured encoder type, or a
    /// long-running systemic pause). Operator-visible so silent skips surface.</summary>
    ConfigurationDrift = 12,

    /// <summary>
    /// Engine-tracked account state has diverged from the broker-reported account state
    /// (e.g. equity or balance variance beyond threshold). Raised by
    /// <c>BrokerPnLReconciliationWorker</c>. Distinct from <see cref="DataQualityIssue"/>
    /// because the data is trustworthy — the engine's bookkeeping is not.
    /// </summary>
    BrokerReconciliation = 13,

    /// <summary>
    /// An ML monitoring pipeline cannot evaluate a model — typically because no
    /// informative prediction logs are reaching the worker. Distinct from
    /// <see cref="MLModelDegraded"/> because the model itself may be fine; the
    /// problem is upstream in logging, serving, or model lifecycle. Operator
    /// response: investigate the prediction-logging pipeline or confirm the model
    /// is still meant to be served.
    /// </summary>
    MLMonitoringStale = 14
}
