namespace LascodiaTradingEngine.Domain.Enums;

/// <summary>
/// Categorises the condition that triggered an alert notification.
/// </summary>
public enum AlertType
{
    /// <summary>Price reached a user-defined level.</summary>
    PriceLevel = 0,

    /// <summary>Account drawdown exceeded the configured threshold.</summary>
    DrawdownBreached = 1,

    /// <summary>A new trade signal was generated by a strategy.</summary>
    SignalGenerated = 2,

    /// <summary>An order was filled at the broker.</summary>
    OrderFilled = 3,

    /// <summary>A position was closed (by SL, TP, or manual action).</summary>
    PositionClosed = 4,

    /// <summary>An ML model's prediction accuracy has degraded below threshold.</summary>
    MLModelDegraded = 5,

    /// <summary>Market data quality issue detected (gaps, stale ticks, etc.).</summary>
    DataQualityIssue = 6,

    /// <summary>Multiple ML models are degrading simultaneously, indicating systemic issues.</summary>
    SystemicMLDegradation = 7,

    /// <summary>Execution or data pipeline latency exceeded the SLA threshold.</summary>
    LatencySla = 8,

    /// <summary>An optimization lifecycle or recovery issue requires operator visibility.</summary>
    OptimizationLifecycleIssue = 9,

    /// <summary>A background worker has crashed (no heartbeat beyond its configured threshold).</summary>
    WorkerCrash = 10,

    /// <summary>All EA instances disconnected — market data unavailable.</summary>
    EADisconnected = 11
}
