using System.Diagnostics.Metrics;

namespace LascodiaTradingEngine.Application.Common.Diagnostics;

/// <summary>
/// Centralized trading engine metrics using <see cref="System.Diagnostics.Metrics"/>.
/// Exposed via Prometheus at <c>/metrics</c>.
///
/// All instruments are created from a single <see cref="Meter"/> so they can be
/// discovered and exported together.
/// </summary>
public sealed class TradingMetrics
{
    public const string MeterName = "LascodiaTradingEngine";

    private readonly Meter _meter;

    // ── Orders ──────────────────────────────────────────────────────────────
    public Counter<long>     OrdersSubmitted        { get; }
    public Counter<long>     OrdersFilled           { get; }
    public Counter<long>     OrdersFailed           { get; }
    public Histogram<double> OrderFillLatencyMs     { get; }
    public Histogram<double> OrderSlippagePips      { get; }

    // ── Signals ─────────────────────────────────────────────────────────────
    public Counter<long>     SignalsGenerated       { get; }
    public Counter<long>     SignalsAccepted        { get; }
    public Counter<long>     SignalsRejected        { get; }

    // ── Positions ───────────────────────────────────────────────────────────
    public Counter<long>     PositionsOpened        { get; }
    public Counter<long>     PositionsClosed        { get; }
    public Histogram<double> PositionPnL            { get; }

    // ── ML ──────────────────────────────────────────────────────────────────
    public Counter<long>     MLTrainingRuns         { get; }
    public Counter<long>     MLTrainingFailures     { get; }
    public Counter<long>     MLPromotions           { get; }
    public Histogram<double> MLTrainingDurationSecs { get; }
    public Histogram<double> MLScoringLatencyMs     { get; }
    public Counter<long>     MLArchitectureSelected { get; }
    public Counter<long>     MLSelectorFallbackDepth { get; }
    public Counter<long>     MLSelectorTrendPenalty  { get; }

    // ── Workers ─────────────────────────────────────────────────────────────
    public Histogram<double> WorkerCycleDurationMs  { get; }
    public Counter<long>     WorkerErrors           { get; }

    // ── Candle Aggregator ──────────────────────────────────────────────
    public Counter<long>     CandlesClosed          { get; }
    public Counter<long>     CandlesSynthetic       { get; }
    public Counter<long>     CandleTicksDropped     { get; }
    public Counter<long>     CandleSlotsPurged      { get; }
    public Counter<long>     CandleTicksSpreadRejected { get; }

    // ── Cache ───────────────────────────────────────────────────────────────
    public Counter<long>     PriceCacheMisses       { get; }

    // ── Simulated Broker ─────────────────────────────────────────────────
    public Counter<long>     SimBrokerFills         { get; }
    public Counter<long>     SimBrokerRejects       { get; }
    public Counter<long>     SimBrokerRequotes      { get; }
    public Counter<long>     SimBrokerDisconnects   { get; }
    public Counter<long>     SimBrokerStopOuts      { get; }
    public Counter<long>     SimBrokerMarginCalls   { get; }
    public Counter<long>     SimBrokerSlTpCloses    { get; }
    public Counter<long>     SimBrokerPendingFills  { get; }
    public Counter<long>     SimBrokerExpiredOrders { get; }
    public Histogram<double> SimBrokerMarginLevel   { get; }
    public Histogram<double> SimBrokerRealizedPnl   { get; }

    public TradingMetrics(IMeterFactory meterFactory)
    {
        _meter = meterFactory.Create(MeterName);

        // Orders
        OrdersSubmitted    = _meter.CreateCounter<long>("trading.orders.submitted", "orders", "Orders submitted to broker");
        OrdersFilled       = _meter.CreateCounter<long>("trading.orders.filled", "orders", "Orders filled by broker");
        OrdersFailed       = _meter.CreateCounter<long>("trading.orders.failed", "orders", "Orders that failed submission");
        OrderFillLatencyMs = _meter.CreateHistogram<double>("trading.orders.fill_latency", "ms", "Broker fill latency");
        OrderSlippagePips  = _meter.CreateHistogram<double>("trading.orders.slippage", "pips", "Fill slippage in pips");

        // Signals
        SignalsGenerated = _meter.CreateCounter<long>("trading.signals.generated", "signals", "Trade signals generated by strategies");
        SignalsAccepted  = _meter.CreateCounter<long>("trading.signals.accepted", "signals", "Signals that passed risk checks");
        SignalsRejected  = _meter.CreateCounter<long>("trading.signals.rejected", "signals", "Signals blocked by risk checks");

        // Positions
        PositionsOpened = _meter.CreateCounter<long>("trading.positions.opened", "positions", "Positions opened");
        PositionsClosed = _meter.CreateCounter<long>("trading.positions.closed", "positions", "Positions closed");
        PositionPnL     = _meter.CreateHistogram<double>("trading.positions.pnl", "USD", "Realized P&L per closed position");

        // ML
        MLTrainingRuns         = _meter.CreateCounter<long>("trading.ml.training_runs", "runs", "ML training runs started");
        MLTrainingFailures     = _meter.CreateCounter<long>("trading.ml.training_failures", "runs", "ML training runs that failed");
        MLPromotions           = _meter.CreateCounter<long>("trading.ml.promotions", "promotions", "ML models promoted to active");
        MLTrainingDurationSecs = _meter.CreateHistogram<double>("trading.ml.training_duration", "s", "ML training duration");
        MLScoringLatencyMs     = _meter.CreateHistogram<double>("trading.ml.scoring_latency", "ms", "ML signal scoring latency");
        MLArchitectureSelected  = _meter.CreateCounter<long>("trading.ml.architecture_selected", "selections", "ML architecture selections by TrainerSelector");
        MLSelectorFallbackDepth = _meter.CreateCounter<long>("trading.ml.selector_fallback_depth", "selections", "TrainerSelector fallback depth reached per selection");
        MLSelectorTrendPenalty  = _meter.CreateCounter<long>("trading.ml.selector_trend_penalty", "penalties", "Architecture score penalised due to declining performance trend");

        // Workers
        WorkerCycleDurationMs = _meter.CreateHistogram<double>("trading.workers.cycle_duration", "ms", "Worker poll cycle duration");
        WorkerErrors          = _meter.CreateCounter<long>("trading.workers.errors", "errors", "Unhandled worker errors");

        // Candle Aggregator
        CandlesClosed      = _meter.CreateCounter<long>("trading.candles.closed", "candles", "Candle bars closed by aggregator");
        CandlesSynthetic   = _meter.CreateCounter<long>("trading.candles.synthetic", "candles", "Synthetic gap-fill candles emitted");
        CandleTicksDropped = _meter.CreateCounter<long>("trading.candles.ticks_dropped", "ticks", "Out-of-order ticks dropped by aggregator");
        CandleSlotsPurged  = _meter.CreateCounter<long>("trading.candles.slots_purged", "slots", "Stale candle slots purged");
        CandleTicksSpreadRejected = _meter.CreateCounter<long>("trading.candles.ticks_spread_rejected", "ticks", "Ticks rejected due to excessive spread");

        // Cache
        PriceCacheMisses = _meter.CreateCounter<long>("trading.cache.price_misses", "misses", "Live price cache misses");

        // Simulated Broker
        SimBrokerFills         = _meter.CreateCounter<long>("trading.sim_broker.fills", "fills", "Simulated broker order fills");
        SimBrokerRejects       = _meter.CreateCounter<long>("trading.sim_broker.rejects", "rejects", "Simulated broker order rejections");
        SimBrokerRequotes      = _meter.CreateCounter<long>("trading.sim_broker.requotes", "requotes", "Simulated broker requotes issued");
        SimBrokerDisconnects   = _meter.CreateCounter<long>("trading.sim_broker.disconnects", "disconnects", "Simulated broker connection failures");
        SimBrokerStopOuts      = _meter.CreateCounter<long>("trading.sim_broker.stop_outs", "stop_outs", "Simulated broker stop-out liquidations");
        SimBrokerMarginCalls   = _meter.CreateCounter<long>("trading.sim_broker.margin_calls", "margin_calls", "Simulated broker margin call warnings");
        SimBrokerSlTpCloses    = _meter.CreateCounter<long>("trading.sim_broker.sl_tp_closes", "closes", "Simulated broker SL/TP position closes");
        SimBrokerPendingFills  = _meter.CreateCounter<long>("trading.sim_broker.pending_fills", "fills", "Simulated broker pending order triggers");
        SimBrokerExpiredOrders = _meter.CreateCounter<long>("trading.sim_broker.expired_orders", "orders", "Simulated broker expired pending orders");
        SimBrokerMarginLevel   = _meter.CreateHistogram<double>("trading.sim_broker.margin_level", "%", "Simulated broker margin level at evaluation");
        SimBrokerRealizedPnl   = _meter.CreateHistogram<double>("trading.sim_broker.realized_pnl", "USD", "Simulated broker realized P&L per close");
    }
}
