using Lascodia.Trading.Engine.SharedDomain.Common;

namespace LascodiaTradingEngine.Domain.Entities;

/// <summary>
/// Defines the risk management rules applied to all positions and orders generated by
/// strategies that reference this profile.
/// </summary>
/// <remarks>
/// A risk profile acts as a guardrail on the engine's automated trading activity.
/// Before any order is submitted, the risk checker validates that the proposed trade
/// does not violate the profile's lot-size, drawdown, exposure, or frequency limits.
/// Multiple strategies can share a single profile; the <see cref="IsDefault"/> flag
/// identifies the fallback profile used when a strategy has no explicit assignment.
/// </remarks>
public class RiskProfile : Entity<long>
{
    /// <summary>Human-readable name for this risk configuration (e.g. "Conservative", "Aggressive").</summary>
    public string  Name                        { get; set; } = string.Empty;

    /// <summary>
    /// Maximum lot size allowed per individual trade.
    /// The risk checker rejects or sizes down any order whose requested lot size exceeds this.
    /// </summary>
    public decimal MaxLotSizePerTrade          { get; set; } = 1m;

    /// <summary>
    /// Maximum percentage of account equity that can be lost in a single trading day.
    /// When this threshold is hit the risk system blocks further orders for the remainder of the day.
    /// </summary>
    public decimal MaxDailyDrawdownPct         { get; set; } = 2m;

    /// <summary>
    /// Maximum percentage of account equity that can be lost in total (peak-to-trough).
    /// A breach triggers circuit-breaker logic that pauses all automated trading.
    /// </summary>
    public decimal MaxTotalDrawdownPct         { get; set; } = 10m;

    /// <summary>
    /// Maximum number of positions that may be open simultaneously across all strategies
    /// using this risk profile. New signals are rejected when this limit is reached.
    /// </summary>
    public int     MaxOpenPositions            { get; set; } = 5;

    /// <summary>
    /// Maximum number of new trades allowed in a 24-hour rolling window.
    /// Prevents over-trading during volatile or news-driven market conditions.
    /// </summary>
    public int     MaxDailyTrades              { get; set; } = 10;

    /// <summary>
    /// Maximum percentage of account equity risked on a single trade.
    /// The lot size is sized down to satisfy this constraint before order submission.
    /// </summary>
    public decimal MaxRiskPerTradePct          { get; set; } = 1m;

    /// <summary>
    /// Maximum percentage of account equity that may be exposed to a single currency pair
    /// at any time, across all open positions on that symbol.
    /// </summary>
    public decimal MaxSymbolExposurePct        { get; set; } = 5m;

    /// <summary>
    /// When <c>true</c>, this profile is used as the system-wide fallback for strategies
    /// that do not have an explicit <see cref="Strategy.RiskProfileId"/> assigned.
    /// Only one profile should have this flag set.
    /// </summary>
    public bool    IsDefault                   { get; set; }

    // ── Drawdown recovery settings ───────────────────────────────────────────

    /// <summary>
    /// Once a drawdown event is detected, the account equity must recover by at least
    /// this percentage before normal lot sizes are restored.
    /// This prevents re-entering full-size trading too early after a losing streak.
    /// </summary>
    public decimal DrawdownRecoveryThresholdPct { get; set; } = 1.5m;

    /// <summary>
    /// Multiplier applied to the standard lot size during the recovery period.
    /// A value of 0.5 means the engine trades at half the normal size until recovery is confirmed.
    /// </summary>
    public decimal RecoveryLotSizeMultiplier    { get; set; } = 0.5m;

    /// <summary>
    /// The equity gain required (as a percentage of current equity) to exit recovery mode
    /// and resume trading at full lot sizes.
    /// </summary>
    public decimal RecoveryExitThresholdPct     { get; set; } = 0.5m;

    /// <summary>Soft-delete flag. Filtered out by the global EF Core query filter.</summary>
    public bool    IsDeleted { get; set; }

    // ── Navigation properties ────────────────────────────────────────────────

    /// <summary>Strategies governed by this risk profile.</summary>
    public virtual ICollection<Strategy> Strategies { get; set; } = new List<Strategy>();
}
