using Lascodia.Trading.Engine.SharedDomain.Common;

namespace LascodiaTradingEngine.Domain.Entities;

/// <summary>
/// Defines the risk management rules applied to all positions and orders generated by
/// strategies that reference this profile.
/// </summary>
/// <remarks>
/// A risk profile acts as a guardrail on the engine's automated trading activity.
/// Before any order is submitted, the risk checker validates that the proposed trade
/// does not violate the profile's lot-size, drawdown, exposure, or frequency limits.
/// Multiple strategies can share a single profile; the <see cref="IsDefault"/> flag
/// identifies the fallback profile used when a strategy has no explicit assignment.
/// </remarks>
public class RiskProfile : Entity<long>
{
    /// <summary>Human-readable name for this risk configuration (e.g. "Conservative", "Aggressive").</summary>
    public string  Name                        { get; set; } = string.Empty;

    /// <summary>
    /// Maximum lot size allowed per individual trade.
    /// The risk checker rejects or sizes down any order whose requested lot size exceeds this.
    /// </summary>
    public decimal MaxLotSizePerTrade          { get; set; } = 1m;

    /// <summary>
    /// Maximum percentage of account equity that can be lost in a single trading day.
    /// When this threshold is hit the risk system blocks further orders for the remainder of the day.
    /// </summary>
    public decimal MaxDailyDrawdownPct         { get; set; } = 2m;

    /// <summary>
    /// Maximum percentage of account equity that can be lost in total (peak-to-trough).
    /// A breach triggers circuit-breaker logic that pauses all automated trading.
    /// </summary>
    public decimal MaxTotalDrawdownPct         { get; set; } = 10m;

    /// <summary>
    /// Maximum number of positions that may be open simultaneously across all strategies
    /// using this risk profile. New signals are rejected when this limit is reached.
    /// </summary>
    public int     MaxOpenPositions            { get; set; } = 5;

    /// <summary>
    /// Maximum number of new trades allowed in a 24-hour rolling window.
    /// Prevents over-trading during volatile or news-driven market conditions.
    /// </summary>
    public int     MaxDailyTrades              { get; set; } = 10;

    /// <summary>
    /// Maximum percentage of account equity risked on a single trade.
    /// The lot size is sized down to satisfy this constraint before order submission.
    /// </summary>
    public decimal MaxRiskPerTradePct          { get; set; } = 1m;

    /// <summary>
    /// Maximum percentage of account equity that may be exposed to a single currency pair
    /// at any time, across all open positions on that symbol.
    /// </summary>
    public decimal MaxSymbolExposurePct        { get; set; } = 5m;

    /// <summary>
    /// Maximum percentage of account equity that may be exposed across all open positions combined.
    /// Prevents over-leveraging the entire account even when individual symbol limits are respected.
    /// </summary>
    public decimal MaxTotalExposurePct         { get; set; } = 50m;

    /// <summary>
    /// When <c>true</c>, every trade signal must have a stop-loss defined.
    /// Signals without a stop-loss are rejected by the risk checker.
    /// </summary>
    public bool    RequireStopLoss             { get; set; }

    /// <summary>
    /// Maximum absolute monetary amount that can be risked on a single trade (in account currency).
    /// Zero means no absolute cap is applied (only percentage-based limits).
    /// </summary>
    public decimal MaxAbsoluteRiskPerTrade     { get; set; }

    /// <summary>
    /// When <c>true</c>, this profile is used as the system-wide fallback for strategies
    /// that do not have an explicit <see cref="Strategy.RiskProfileId"/> assigned.
    /// Only one profile should have this flag set.
    /// </summary>
    public bool    IsDefault                   { get; set; }

    // ── Drawdown recovery settings ───────────────────────────────────────────

    /// <summary>
    /// Once a drawdown event is detected, the account equity must recover by at least
    /// this percentage before normal lot sizes are restored.
    /// This prevents re-entering full-size trading too early after a losing streak.
    /// </summary>
    public decimal DrawdownRecoveryThresholdPct { get; set; } = 1.5m;

    /// <summary>
    /// Multiplier applied to the standard lot size during the recovery period.
    /// A value of 0.5 means the engine trades at half the normal size until recovery is confirmed.
    /// </summary>
    public decimal RecoveryLotSizeMultiplier    { get; set; } = 0.5m;

    /// <summary>
    /// The equity gain required (as a percentage of current equity) to exit recovery mode
    /// and resume trading at full lot sizes.
    /// </summary>
    public decimal RecoveryExitThresholdPct     { get; set; } = 0.5m;

    /// <summary>
    /// Minimum distance in pips between entry price and stop-loss.
    /// Prevents signals with impractically tight stops that would be stopped out by spread/slippage.
    /// Zero means no minimum distance is enforced.
    /// </summary>
    public decimal MinStopLossDistancePips { get; set; }

    /// <summary>
    /// Minimum required risk-to-reward ratio when both SL and TP are defined.
    /// Calculated as |TP - Entry| / |SL - Entry|. Zero means no minimum RR is enforced.
    /// </summary>
    public decimal MinRiskRewardRatio { get; set; }

    /// <summary>
    /// Maximum number of open positions allowed on a single symbol.
    /// Zero means no per-symbol limit is enforced (only the global <see cref="MaxOpenPositions"/> applies).
    /// </summary>
    public int MaxPositionsPerSymbol { get; set; }

    /// <summary>
    /// Number of consecutive losing trades that triggers a temporary trading pause.
    /// Zero means no consecutive loss gate is applied.
    /// </summary>
    public int MaxConsecutiveLosses { get; set; }

    /// <summary>
    /// Multiplier applied to risk per trade for positions held over a weekend or holiday gap.
    /// Gap risk is unhedgeable, so the effective risk is scaled up before comparing to limits.
    /// 1.0 means no adjustment. Typical values: 1.5–2.0.
    /// </summary>
    public decimal WeekendGapRiskMultiplier { get; set; } = 1.0m;

    /// <summary>
    /// Maximum number of correlated open positions allowed before new signals in the same
    /// correlation group are rejected. Zero means the correlated exposure check is disabled.
    /// </summary>
    public int MaxCorrelatedPositions { get; set; }

    /// <summary>
    /// Minimum account equity (in account currency) below which all trading is halted.
    /// Provides an absolute floor regardless of percentage-based drawdown limits.
    /// Zero means no minimum equity floor is enforced.
    /// </summary>
    public decimal MinEquityFloor { get; set; }

    /// <summary>Soft-delete flag. Filtered out by the global EF Core query filter.</summary>
    public bool    IsDeleted { get; set; }

    // ── Navigation properties ────────────────────────────────────────────────

    /// <summary>Strategies governed by this risk profile.</summary>
    public virtual ICollection<Strategy> Strategies { get; set; } = new List<Strategy>();
}
