using Lascodia.Trading.Engine.SharedDomain.Common;
using LascodiaTradingEngine.Domain.Enums;

namespace LascodiaTradingEngine.Domain.Entities;

/// <summary>
/// Represents a named, configurable trading strategy that the engine monitors and executes.
/// Each strategy is immutably bound to a single algorithm family, symbol, and timeframe; clone
/// it as a new candidate to retarget. Tunable parameters live in <see cref="ParametersJson"/>.
/// </summary>
/// <remarks>
/// Lifecycle: strategies start <see cref="StrategyStatus.Paused"/> and must be explicitly
/// activated. <see cref="Workers.StrategyHealthWorker"/> automatically pauses a strategy when
/// its health score drops below the critical threshold, and queues an
/// <see cref="OptimizationRun"/> to find better parameters.
/// </remarks>
public class Strategy : Entity<long>
{
    /// <summary>Human-readable display name (e.g. "EUR/USD MA Cross v2").</summary>
    public string  Name          { get; set; } = string.Empty;

    /// <summary>Optional free-text description of the strategy's intent and logic.</summary>
    public string  Description   { get; set; } = string.Empty;

    /// <summary>
    /// The algorithm family this strategy belongs to.
    /// Determines which <c>IStrategyEvaluator</c> is invoked at signal-generation time.
    /// Immutable after creation: changing the evaluator would invalidate all historical
    /// performance, ML calibration, and screening results tied to this strategy.
    /// </summary>
    public StrategyType  StrategyType  { get; init; } = StrategyType.Custom;

    /// <summary>
    /// The currency pair or instrument this strategy trades (e.g. "EURUSD", "GBPUSD").
    /// Must match the symbol used in <see cref="Candle"/> and <see cref="TradeSignal"/> records.
    /// Immutable after creation so validation history and lifecycle decisions remain tied to a
    /// stable market identity.
    /// </summary>
    public string  Symbol        { get; init; } = string.Empty;

    /// <summary>
    /// The chart timeframe the strategy evaluates (e.g. H1, M15).
    /// Candle data is filtered by this value when building the indicator window.
    /// Immutable after creation so queued validation runs and live qualification remain coherent.
    /// </summary>
    public Timeframe  Timeframe     { get; init; } = Timeframe.H1;

    /// <summary>
    /// Strategy-specific tunable parameters stored as a JSON object.
    /// The exact keys depend on the <see cref="StrategyType"/>:
    /// e.g. <c>{"FastPeriod":9,"SlowPeriod":21}</c> for a moving-average crossover.
    /// Updated by <see cref="OptimizationRun"/> when a better parameter set is found.
    /// </summary>
    public string  ParametersJson { get; set; } = "{}";

    /// <summary>
    /// Operational state of the strategy.
    /// Only <see cref="StrategyStatus.Active"/> strategies are evaluated on price updates.
    /// </summary>
    public StrategyStatus  Status        { get; set; } = StrategyStatus.Paused;

    /// <summary>
    /// Records which subsystem paused this strategy (e.g. "ExecutionQuality", "DrawdownRecovery",
    /// "StrategyHealth", "Manual"). Used to prevent one subsystem from auto-resuming a strategy
    /// that was paused by a different, higher-priority subsystem. Null when strategy is active.
    /// </summary>
    public string? PauseReason { get; set; }

    /// <summary>Optimistic concurrency token — auto-incremented by the database on every update.</summary>
    public uint RowVersion { get; set; }

    /// <summary>
    /// Foreign key to the <see cref="RiskProfile"/> that governs position sizing and
    /// drawdown limits for signals generated by this strategy.
    /// Nullable — falls back to the system default risk profile when null.
    /// </summary>
    public long?   RiskProfileId { get; set; }

    /// <summary>UTC timestamp when this strategy was first created.</summary>
    public DateTime CreatedAt    { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// When this strategy was generated by the EvolutionaryStrategyGenerator,
    /// the parent strategy whose parameters were mutated to produce it. Null for
    /// hand-authored / template-screened strategies (the common case).
    /// </summary>
    public long? ParentStrategyId { get; set; }

    /// <summary>
    /// Distance from the original ancestor in the evolutionary lineage (0 for
    /// hand-authored / first-generation, parent.Generation+1 for offspring).
    /// Used by the generator to enforce a max generation depth so the search
    /// doesn't drift indefinitely from the original strategy template.
    /// </summary>
    public int Generation { get; set; }

    // ── Lifecycle governance (Improvement 12.3) ──────────────────────────────

    /// <summary>
    /// Graduated lifecycle stage: Draft → PaperTrading → BacktestQualified → ShadowLive → Approved → Active.
    /// Each stage has a minimum duration enforced by the engine. New strategies start as Draft.
    /// </summary>
    public StrategyLifecycleStage LifecycleStage { get; set; } = StrategyLifecycleStage.Draft;

    /// <summary>When the strategy entered its current lifecycle stage.</summary>
    public DateTime? LifecycleStageEnteredAt { get; set; }

    // ── Capacity estimation (Improvement 9.1) ────────────────────────────────

    /// <summary>
    /// Maximum lot size the strategy can absorb before expected alpha is eroded by market impact.
    /// Computed by the StrategyCapacityWorker. Null until first capacity estimate.
    /// </summary>
    public decimal? EstimatedCapacityLots { get; set; }

    // ── Gradual parameter rollout ─────────────────────────────────────────────

    /// <summary>
    /// Percentage of signals that use the new (optimized) parameters. Starts at 25% after
    /// auto-approval and ramps to 100% after N successful signals. When null or 100, all
    /// signals use the current <see cref="ParametersJson"/>.
    /// </summary>
    public int? RolloutPct { get; set; }

    /// <summary>
    /// Snapshot of the pre-optimization parameters. Used for rollback if the new params
    /// underperform during the gradual rollout window. Null when no rollout is active.
    /// </summary>
    public string? RollbackParametersJson { get; set; }

    /// <summary>
    /// UTC timestamp when the current gradual rollout started. Used to enforce the
    /// observation window and trigger automatic rollback if performance degrades.
    /// </summary>
    public DateTime? RolloutStartedAt { get; set; }

    /// <summary>
    /// ID of the optimization run that triggered the current rollout. Links the rollout
    /// to its approval context for audit trail.
    /// </summary>
    public long? RolloutOptimizationRunId { get; set; }

    /// <summary>How many consecutive rollout-evaluation failures have been observed.</summary>
    public int RolloutEvaluationFailureCount { get; set; }

    /// <summary>Last rollout-evaluation failure message recorded for alerting/debugging.</summary>
    public string? RolloutLastFailureMessage { get; set; }

    // ── Screening metadata (auto-generated strategies) ───────────────────────

    /// <summary>
    /// Structured screening metrics serialised as JSON. Populated by the StrategyGenerationWorker
    /// for auto-generated strategies. Contains IS/OOS metrics, equity R², Monte Carlo p-value,
    /// walk-forward results, and generation context. Null for manually created strategies.
    /// </summary>
    public string? ScreeningMetricsJson { get; set; }

    /// <summary>UTC timestamp when the strategy was pruned from the generation pipeline.</summary>
    public DateTime? PrunedAtUtc { get; set; }

    /// <summary>Generation cycle identifier for auto-generated strategies.</summary>
    public string? GenerationCycleId { get; set; }

    /// <summary>Stable candidate identifier used to link validation artifacts back to generation.</summary>
    public string? GenerationCandidateId { get; set; }

    /// <summary>Initial validation priority assigned by strategy generation.</summary>
    public int ValidationPriority { get; set; }

    /// <summary>Soft-delete flag. Filtered out by the global EF Core query filter.</summary>
    public bool    IsDeleted     { get; set; }

    // ── Navigation properties ────────────────────────────────────────────────

    /// <summary>The risk profile governing this strategy's position sizing and limits.</summary>
    public virtual RiskProfile? RiskProfile { get; set; }

    /// <summary>All trade signals generated by this strategy.</summary>
    public virtual ICollection<TradeSignal> TradeSignals { get; set; } = new List<TradeSignal>();

    /// <summary>Orders placed as a result of this strategy's signals.</summary>
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    /// <summary>Historical backtest runs executed against this strategy.</summary>
    public virtual ICollection<BacktestRun> BacktestRuns { get; set; } = new List<BacktestRun>();

    /// <summary>Parameter optimisation runs queued or completed for this strategy.</summary>
    public virtual ICollection<OptimizationRun> OptimizationRuns { get; set; } = new List<OptimizationRun>();

    /// <summary>Walk-forward validation runs that measure out-of-sample robustness.</summary>
    public virtual ICollection<WalkForwardRun> WalkForwardRuns { get; set; } = new List<WalkForwardRun>();

    /// <summary>Capital allocation weights assigned to this strategy by the portfolio rebalancer.</summary>
    public virtual ICollection<StrategyAllocation> Allocations { get; set; } = new List<StrategyAllocation>();

    /// <summary>Periodic health snapshots (win rate, profit factor, drawdown) used by the health worker.</summary>
    public virtual ICollection<StrategyPerformanceSnapshot> PerformanceSnapshots { get; set; } = new List<StrategyPerformanceSnapshot>();

    /// <summary>Execution quality measurements (slippage, fill rate) for orders tied to this strategy.</summary>
    public virtual ICollection<ExecutionQualityLog> ExecutionQualityLogs { get; set; } = new List<ExecutionQualityLog>();

    // ── Runtime operational state (persisted by StrategyWorker) ─────────────────
    // These fields shadow in-memory ConcurrentDictionaries in StrategyWorker so that
    // cooldown / circuit-breaker state survives process restarts. Without them, every
    // engine restart gave all strategies a zero-cooldown window, producing a thundering
    // herd of fresh signals in the first 5 minutes while the warm-up timer rebuilt
    // state. Written back periodically by the expiry-sweep; tolerant of ≤5 min staleness.

    /// <summary>UTC timestamp of the most recent TradeSignal emitted by this strategy.
    /// Null if the strategy has never emitted a signal. Used to enforce per-strategy
    /// cooldown across process restarts.</summary>
    public DateTime? LastSignalAt { get; set; }

    /// <summary>Consecutive failed evaluations (exceptions / timeouts) since the last
    /// successful evaluation. When this crosses the worker's configured threshold, the
    /// circuit opens and is reflected in <see cref="CircuitOpenedAt"/>.</summary>
    public int ConsecutiveEvaluationFailures { get; set; }

    /// <summary>UTC timestamp when the evaluation circuit breaker opened for this
    /// strategy. Null while the circuit is closed. Set when consecutive failures
    /// exceed the threshold; cleared on successful probe recovery.</summary>
    public DateTime? CircuitOpenedAt { get; set; }
}
