using Lascodia.Trading.Engine.SharedDomain.Common;
using LascodiaTradingEngine.Domain.Enums;

namespace LascodiaTradingEngine.Domain.Entities;

/// <summary>
/// Represents a named, configurable trading strategy that the engine monitors and executes.
/// Each strategy is bound to a single symbol and timeframe and carries its own parameter set
/// serialised as JSON so new strategy types can be added without schema changes.
/// </summary>
/// <remarks>
/// Lifecycle: strategies start <see cref="StrategyStatus.Paused"/> and must be explicitly
/// activated. <see cref="Workers.StrategyHealthWorker"/> automatically pauses a strategy when
/// its health score drops below the critical threshold, and queues an
/// <see cref="OptimizationRun"/> to find better parameters.
/// </remarks>
public class Strategy : Entity<long>
{
    /// <summary>Human-readable display name (e.g. "EUR/USD MA Cross v2").</summary>
    public string  Name          { get; set; } = string.Empty;

    /// <summary>Optional free-text description of the strategy's intent and logic.</summary>
    public string  Description   { get; set; } = string.Empty;

    /// <summary>
    /// The algorithm family this strategy belongs to.
    /// Determines which <c>IStrategyEvaluator</c> is invoked at signal-generation time.
    /// </summary>
    public StrategyType  StrategyType  { get; set; } = StrategyType.Custom;

    /// <summary>
    /// The currency pair or instrument this strategy trades (e.g. "EURUSD", "GBPUSD").
    /// Must match the symbol used in <see cref="Candle"/> and <see cref="TradeSignal"/> records.
    /// </summary>
    public string  Symbol        { get; set; } = string.Empty;

    /// <summary>
    /// The chart timeframe the strategy evaluates (e.g. H1, M15).
    /// Candle data is filtered by this value when building the indicator window.
    /// </summary>
    public Timeframe  Timeframe     { get; set; } = Timeframe.H1;

    /// <summary>
    /// Strategy-specific tunable parameters stored as a JSON object.
    /// The exact keys depend on the <see cref="StrategyType"/>:
    /// e.g. <c>{"FastPeriod":9,"SlowPeriod":21}</c> for a moving-average crossover.
    /// Updated by <see cref="OptimizationRun"/> when a better parameter set is found.
    /// </summary>
    public string  ParametersJson { get; set; } = "{}";

    /// <summary>
    /// Operational state of the strategy.
    /// Only <see cref="StrategyStatus.Active"/> strategies are evaluated on price updates.
    /// </summary>
    public StrategyStatus  Status        { get; set; } = StrategyStatus.Paused;

    /// <summary>
    /// Foreign key to the <see cref="RiskProfile"/> that governs position sizing and
    /// drawdown limits for signals generated by this strategy.
    /// Nullable — falls back to the system default risk profile when null.
    /// </summary>
    public long?   RiskProfileId { get; set; }

    /// <summary>UTC timestamp when this strategy was first created.</summary>
    public DateTime CreatedAt    { get; set; } = DateTime.UtcNow;

    /// <summary>Soft-delete flag. Filtered out by the global EF Core query filter.</summary>
    public bool    IsDeleted     { get; set; }

    // ── Navigation properties ────────────────────────────────────────────────

    /// <summary>The risk profile governing this strategy's position sizing and limits.</summary>
    public virtual RiskProfile? RiskProfile { get; set; }

    /// <summary>All trade signals generated by this strategy.</summary>
    public virtual ICollection<TradeSignal> TradeSignals { get; set; } = new List<TradeSignal>();

    /// <summary>Orders placed as a result of this strategy's signals.</summary>
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    /// <summary>Historical backtest runs executed against this strategy.</summary>
    public virtual ICollection<BacktestRun> BacktestRuns { get; set; } = new List<BacktestRun>();

    /// <summary>Parameter optimisation runs queued or completed for this strategy.</summary>
    public virtual ICollection<OptimizationRun> OptimizationRuns { get; set; } = new List<OptimizationRun>();

    /// <summary>Walk-forward validation runs that measure out-of-sample robustness.</summary>
    public virtual ICollection<WalkForwardRun> WalkForwardRuns { get; set; } = new List<WalkForwardRun>();

    /// <summary>Capital allocation weights assigned to this strategy by the portfolio rebalancer.</summary>
    public virtual ICollection<StrategyAllocation> Allocations { get; set; } = new List<StrategyAllocation>();

    /// <summary>Periodic health snapshots (win rate, profit factor, drawdown) used by the health worker.</summary>
    public virtual ICollection<StrategyPerformanceSnapshot> PerformanceSnapshots { get; set; } = new List<StrategyPerformanceSnapshot>();

    /// <summary>Execution quality measurements (slippage, fill rate) for orders tied to this strategy.</summary>
    public virtual ICollection<ExecutionQualityLog> ExecutionQualityLogs { get; set; } = new List<ExecutionQualityLog>();
}
