using FluentValidation;
using MediatR;
using Microsoft.EntityFrameworkCore;
using Lascodia.Trading.Engine.SharedApplication.Common.Models;
using LascodiaTradingEngine.Application.Common.Interfaces;
using LascodiaTradingEngine.Domain.Enums;

namespace LascodiaTradingEngine.Application.ExpertAdvisor.Commands.ProcessSignalFeedback;

// ── DTO ──────────────────────────────────────────────────────────────────

/// <summary>
/// Feedback for a single trade signal from the EA, indicating why it could not be executed.
/// </summary>
public class SignalFeedbackItem
{
    /// <summary>Database ID of the trade signal this feedback applies to.</summary>
    public long SignalId { get; set; }

    /// <summary>Reason the signal was not executed: "Expired", "SpreadDeferred", "Dropped", "SafetyRejected", "MarketClosed", or "SymbolNotFound".</summary>
    public string Reason { get; set; } = string.Empty;

    /// <summary>Optional additional context from the EA (e.g. current spread value, error message).</summary>
    public string? Details { get; set; }

    /// <summary>UTC time when the feedback was generated by the EA.</summary>
    public DateTime Timestamp { get; set; }
}

// ── Command ──────────────────────────────────────────────────────────────

/// <summary>
/// Processes feedback from an EA instance about trade signals it could not execute.
/// Transitions signals to Expired or Rejected status based on the feedback reason.
/// SpreadDeferred signals are left in their current state for potential later execution.
/// Returns the count of signals whose status was updated.
/// </summary>
public class ProcessSignalFeedbackCommand : IRequest<ResponseData<int>>
{
    /// <summary>Unique identifier of the EA instance providing the feedback.</summary>
    public required string InstanceId { get; set; }

    /// <summary>List of signal feedback items to process.</summary>
    public List<SignalFeedbackItem> Feedback { get; set; } = new();
}

// ── Validator ────────────────────────────────────────────────────────────

/// <summary>
/// Validates InstanceId is non-empty, Feedback list is non-empty, and each item has a positive SignalId and non-empty Reason.
/// </summary>
public class ProcessSignalFeedbackCommandValidator : AbstractValidator<ProcessSignalFeedbackCommand>
{
    public ProcessSignalFeedbackCommandValidator()
    {
        RuleFor(x => x.InstanceId).NotEmpty().WithMessage("InstanceId cannot be empty");
        RuleFor(x => x.Feedback).NotEmpty().WithMessage("Feedback list cannot be empty");
        RuleForEach(x => x.Feedback).ChildRules(item =>
        {
            item.RuleFor(x => x.SignalId).GreaterThan(0);
            item.RuleFor(x => x.Reason).NotEmpty();
        });
    }
}

// ── Handler ──────────────────────────────────────────────────────────────

/// <summary>
/// Handles signal feedback processing. Batch-loads referenced signals, then for each feedback item:
/// Expired/MarketClosed reasons set the signal to Expired; Dropped/SafetyRejected/SymbolNotFound
/// reasons set it to Rejected; SpreadDeferred is logged but does not change signal status.
/// Only signals in Pending or Approved state are affected.
/// </summary>
public class ProcessSignalFeedbackCommandHandler : IRequestHandler<ProcessSignalFeedbackCommand, ResponseData<int>>
{
    private readonly IWriteApplicationDbContext _context;

    public ProcessSignalFeedbackCommandHandler(IWriteApplicationDbContext context)
    {
        _context = context;
    }

    public async Task<ResponseData<int>> Handle(ProcessSignalFeedbackCommand request, CancellationToken cancellationToken)
    {
        int processed = 0;
        var db = _context.GetDbContext();

        // Get all signal IDs from the feedback batch
        var signalIds = request.Feedback.Select(f => f.SignalId).Distinct().ToList();

        // Batch-load signals that are still in actionable states
        var signals = await db.Set<Domain.Entities.TradeSignal>()
            .Where(s => signalIds.Contains(s.Id) && !s.IsDeleted)
            .ToListAsync(cancellationToken);

        var signalMap = signals.ToDictionary(s => s.Id);

        foreach (var item in request.Feedback)
        {
            if (!signalMap.TryGetValue(item.SignalId, out var signal))
                continue;

            // Only update signals that are still pending or approved (not already executed/rejected/expired)
            if (signal.Status != TradeSignalStatus.Pending && signal.Status != TradeSignalStatus.Approved)
                continue;

            switch (item.Reason)
            {
                case "Expired":
                case "MarketClosed":
                    signal.Status = TradeSignalStatus.Expired;
                    signal.RejectionReason = $"EA: {item.Reason}" + (item.Details != null ? $" - {item.Details}" : "");
                    processed++;
                    break;

                case "Dropped":
                case "SafetyRejected":
                case "SymbolNotFound":
                    signal.Status = TradeSignalStatus.Rejected;
                    signal.RejectionReason = $"EA: {item.Reason}" + (item.Details != null ? $" - {item.Details}" : "");
                    processed++;
                    break;

                case "SpreadDeferred":
                    // Don't change status - just log the deferral. Signal stays in Pending/Approved.
                    // Engine can use this for monitoring but the EA may still execute it.
                    break;
            }
        }

        if (processed > 0)
            await _context.SaveChangesAsync(cancellationToken);

        return ResponseData<int>.Init(processed, true, $"Processed {processed} signal feedback items", "00");
    }
}
