using Lascodia.Trading.Engine.EventBus.Events;

namespace LascodiaTradingEngine.Application.Common.Events;

public record TradeSignalCreatedIntegrationEvent : IntegrationEvent
{
    public long    SequenceNumber { get; init; } = EventSequence.Next();

    /// <summary>
    /// Correlation ID that links this signal through the entire trade lifecycle:
    /// signal creation → Tier 1 validation → order creation → fill → position.
    /// Generated by StrategyWorker when the signal is created; propagated by downstream handlers.
    /// </summary>
    public string  CorrelationId { get; init; } = Guid.NewGuid().ToString("N");

    public long    TradeSignalId { get; init; }
    public long    StrategyId    { get; init; }
    public string  Symbol        { get; init; } = string.Empty;
    public string  Direction     { get; init; } = string.Empty;
    public decimal EntryPrice    { get; init; }
}
